#!/usr/bin/env bash
# .claude/hooks/fence.sh — generated by /setup (scripts/gen_hooks.sh) from
# .claude/budgets.json. Do not hand-edit SLICE_ROOT/SHARED_ROOT/
# FROZEN_PATTERNS below — edit budgets.json and re-run /setup instead;
# drift_audit.sh flags it if this file and budgets.json ever disagree.
set -eo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')

# Only file-mutating tools get fenced; Read/Bash/Grep/etc. pass straight
# through untouched.
case "$TOOL_NAME" in
  Edit|Write|MultiEdit|NotebookEdit) ;;
  *) exit 0 ;;
esac

# --- generated from budgets.json — edit there, not here ---
SLICE_ROOT=src/grim
SHARED_ROOT=src/grim
FROZEN_PATTERNS=(
  'src/grim/db.py'
  'src/grim/cli.py'
  '.claude/**'
  'CLAUDE.md'
  'pyproject.toml'
  'uv.lock'
  '.github/workflows/**'
)
BASELINE_PATTERNS=(
  '.claude/mypy-baseline.txt'
)
# --- end generated block ---

decide() {
  # $1 = deny|ask, $2 = human-readable reason. Emits the PreToolUse JSON
  # contract and exits 0 — the JSON itself carries the decision, exit code
  # is not what communicates deny/ask here (that's the exit-2 path, which
  # this script doesn't use so it can express "ask", not just allow/deny).
  jq -n --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: $d, permissionDecisionReason: $r}}'
  exit 0
}

matches_any() {
  local path="$1"; shift
  for pat in "$@"; do
    # Unquoted case patterns glob-match the whole string (no path-separator
    # special-casing the way filename expansion has) — "shared/**" matches
    # "shared/x/y.ts" the same as "shared/*" would here.
    case "$path" in
      $pat) return 0 ;;
    esac
  done
  return 1
}

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
TOUCHED=()
FP=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -n "$FP" ] && TOUCHED+=("$FP")

for ABS in "${TOUCHED[@]}"; do
  REL="${ABS#$REPO_ROOT/}"

  # Append-only guard for the two agent-writable ledgers (constitution §2
  # and §5: ABSTRACTIONS.md, RATCHET.md). A write only passes silently if
  # the new content still starts with the file's current content — a
  # heuristic for "this is a pure append," not a real diff. Anything else
  # (rewrite, mid-file insertion, deletion) gets asked, never silently
  # allowed. Checked for BOTH Edit (old_string/new_string) and Write (full
  # `content`, compared against what's actually on disk) — a Write that
  # replaces the whole file is exactly the case an Edit-only check would
  # have missed.
  if [ "$REL" = "ABSTRACTIONS.md" ] || [ "$REL" = "RATCHET.md" ]; then
    case "$TOOL_NAME" in
      Edit)
        OLD=$(echo "$INPUT" | jq -r '.tool_input.old_string // empty')
        NEW=$(echo "$INPUT" | jq -r '.tool_input.new_string // empty')
        case "$NEW" in
          "$OLD"*) : ;;
          *) decide ask "$REL is append-only — this edit doesn't look like a pure append. Confirm before writing." ;;
        esac
        ;;
      Write)
        if [ -f "$ABS" ]; then
          NEW_CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // empty')
          CURRENT=$(cat "$ABS" 2>/dev/null || true)
          case "$NEW_CONTENT" in
            "$CURRENT"*) : ;;
            *) decide ask "$REL is append-only — this Write doesn't look like a pure append over the existing file. Confirm before writing." ;;
          esac
        fi
        ;;
    esac
  fi

  # Checked BEFORE the frozen-paths ask below: a baseline file could also
  # match a frozen pattern (e.g. it lives under .claude/**), and deny must
  # win over ask when both apply — "never by hand" allows no confirmation
  # path at all, unlike a frozen-path write.
  if matches_any "$REL" "${BASELINE_PATTERNS[@]}"; then
    decide deny "$REL is a tool-written baseline/suppression file — never edited by hand. Use the /ratchet skill's prune.sh (or the underlying tool: eslint --prune-suppressions, depcruise-baseline, etc.) via Bash instead."
  fi

  if matches_any "$REL" "${FROZEN_PATTERNS[@]}"; then
    decide ask "$REL is a frozen path (see CLAUDE.md's Frozen paths section) — confirm this write."
  fi

  if [ -n "$SLICE_ROOT" ] && [ -n "${TASK_SLICE:-}" ]; then
    case "$REL" in
      "$SLICE_ROOT"/*)
        case "$REL" in
          "$SLICE_ROOT/$TASK_SLICE"/*) : ;;
          *) decide deny "$REL is outside the active slice (\$TASK_SLICE=$TASK_SLICE). Cross-slice code goes through $SHARED_ROOT/, not a direct write." ;;
        esac
        ;;
    esac
  fi
done

exit 0
