#!/usr/bin/env bash
# .claude/hooks/gate.sh — generated by /setup (scripts/gen_hooks.sh) from
# .claude/budgets.json. Do not hand-edit the commands/DIFF_BUDGET below —
# edit budgets.json and re-run /setup.
set -eo pipefail

# A clean working tree means nothing was touched this turn — always allow
# stopping. This is what keeps the gate from ever blocking a pure Q&A turn,
# and from re-triggering itself indefinitely on an unrelated conversation.
if [ -z "$(git status --porcelain 2>/dev/null)" ]; then exit 0; fi

FAILS=()
run() {
  local label="$1"; shift
  local log; log="$(mktemp)"
  if ! "$@" >"$log" 2>&1; then
    FAILS+=("$label: $(tail -5 "$log" | tr '\n' ' ')")
  fi
  rm -f "$log"
}

run format uv run ruff format --check .
run typecheck uv run mypy
run lint uv run ruff check .
run test uv run pytest

DIFF_BUDGET=300
# --shortstat prints "N files changed, A insertions(+), D deletions(-)" —
# sum the insertion/deletion counts as a proxy for "diff size." The
# trailing `|| true` matters: under `pipefail`, a diff with nothing to
# match (e.g. a rename-only change) makes the inner grep -oE fail and
# poisons this whole assignment even though the final awk stage succeeds
# — without the guard, THIS GATE ITSELF would silently die on `set -e`,
# and a Stop hook that exits non-zero-but-not-2 fails OPEN (Claude Code
# treats it as a non-blocking error and just continues) — worse than no
# gate at all. Confirmed by hand while building this generator.
DIFF_LINES=$(git diff --shortstat HEAD 2>/dev/null | grep -oE '[0-9]+ (insertion|deletion)' | grep -oE '[0-9]+' | awk '{s+=$1} END {print s+0}' || true)
if [ -n "$DIFF_LINES" ] && [ "$DIFF_LINES" -gt "$DIFF_BUDGET" ]; then
  FAILS+=("diff: ${DIFF_LINES} lines changed, budget is ${DIFF_BUDGET} — generated artifacts (baselines, lockfiles) are exempt if split into their own commit")
fi

if [ ${#FAILS[@]} -gt 0 ]; then
  REASON=$(printf '%s\n' "${FAILS[@]}")
  jq -n --arg r "$REASON" '{decision: "block", reason: $r}'
fi
exit 0
