/**
 * .pi/extensions/guardrails/index.ts — generated by /setup
 * (scripts/gen_pi_extension.sh) from .claude/budgets.json.
 *
 * Pi-native port of .claude/hooks/{fence,feedback,gate}.sh: same
 * enforcement (frozen-path ask, baseline-path deny, append-only ledgers,
 * git-diff-inferred slice gating, format/lint/typecheck/test gate),
 * expressed against Pi's tool_call / tool_result / agent_settled events
 * instead of Claude Code's PreToolUse/PostToolUse/Stop hook contract.
 * Docs: https://github.com/earendil-works/pi/blob/main/packages/coding-agent/docs/extensions.md
 *
 * Do not hand-edit the generated-constants block below — edit
 * .claude/budgets.json and re-run /setup instead; drift_audit.sh flags it
 * if this file and budgets.json ever disagree.
 */
import { isToolCallEventType, isEditToolResult, isWriteToolResult, type ExtensionAPI, type ExtensionContext, type ToolCallEvent, type ToolCallEventResult, type ToolResultEvent } from "@earendil-works/pi-coding-agent";
import { readFileSync, existsSync } from "node:fs";
import { isAbsolute, relative, resolve as resolvePath } from "node:path";

// --- generated from budgets.json — edit there, not here ---
const SLICE_ROOT: string = "src/grim";
const SHARED_ROOT: string = "src/grim";
const FROZEN_PATTERNS: string[] = ["src/grim/db.py","src/grim/cli.py",".claude/**","CLAUDE.md","pyproject.toml","uv.lock",".github/workflows/**"];
const BASELINE_PATTERNS: string[] = [".claude/mypy-baseline.txt"];
const DIFF_BUDGET: number = 300;
const CMD_FORMAT: string = "uv run ruff format --check .";
const CMD_TYPECHECK: string = "uv run mypy";
const CMD_LINT: string = "uv run ruff check .";
const CMD_TEST: string = "uv run pytest";
// --- end generated block ---

// ---- path matching (mirrors fence.sh's bash `case` glob matching) --------
// Minimal glob->regex: `**` matches anything including `/`, `*` matches
// anything except `/`, everything else is escaped literally. Enough for
// the "dir/**" / "dir/*.ext" shapes budgets.json actually produces — not
// a full minimatch implementation, same deliberately-narrow scope as the
// bash version's `case` patterns.
function globToRegExp(glob: string): RegExp {
  const escaped = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  // Single-pass replace with a callback, matching the LONGER alternative
  // (`\*\*`) first via alternation order — no intermediate placeholder
  // character needed. (An earlier version used a literal space as a
  // placeholder between two separate `.replace()` calls; it round-tripped
  // through this file's generation as a stray NUL byte instead of a
  // space, silently corrupting the regex. Matching directly in one pass
  // sidesteps the whole class of bug rather than finding a "safer"
  // placeholder character.)
  const withStars = escaped.replace(/\*\*|\*/g, (m) => (m === "**" ? ".*" : "[^/]*"));
  return new RegExp(`^${withStars}$`);
}

function matchesAny(relPath: string, patterns: string[]): boolean {
  return patterns.some((p) => globToRegExp(p).test(relPath));
}

function sliceOf(relPath: string): string {
  const prefix = `${SLICE_ROOT}/`;
  const rest = relPath.startsWith(prefix) ? relPath.slice(prefix.length) : relPath;
  const idx = rest.indexOf("/");
  return idx === -1 ? rest : rest.slice(0, idx);
}

// repoRoot is memoized per extension lifetime — `ctx.cwd` doesn't change
// mid-session, so there's no need to re-resolve `git rev-parse
// --show-toplevel` on every single tool call the way that would suggest.
let cachedRepoRoot: string | undefined;
async function repoRoot(pi: ExtensionAPI, ctx: ExtensionContext): Promise<string> {
  if (cachedRepoRoot) return cachedRepoRoot;
  try {
    const { stdout, code } = await pi.exec("git", ["rev-parse", "--show-toplevel"], { cwd: ctx.cwd });
    cachedRepoRoot = code === 0 ? stdout.trim() : ctx.cwd;
  } catch {
    cachedRepoRoot = ctx.cwd;
  }
  return cachedRepoRoot;
}

function toRelPath(rawPath: string, cwd: string, root: string): string {
  const abs = isAbsolute(rawPath) ? rawPath : resolvePath(cwd, rawPath);
  return relative(root, abs);
}

// The slice-scoping stand-in for a manually-set env var (same design as
// the bash fence's `active_slices`): whatever slice(s) currently have
// UNCOMMITTED changes (staged, unstaged, or untracked — `git status
// --porcelain` covers all three). A clean tree means no slice is active
// yet, so the next write picks one implicitly.
async function activeSlices(pi: ExtensionAPI, ctx: ExtensionContext, root: string): Promise<string[]> {
  const { stdout } = await pi.exec("git", ["status", "--porcelain"], { cwd: root });
  const slices = new Set<string>();
  for (const rawLine of stdout.split("\n")) {
    if (!rawLine) continue;
    // Porcelain lines are "XY path" (3-char prefix) or "XY old -> new" for
    // renames, where only the new path matters here.
    let p = rawLine.slice(3);
    const arrow = p.indexOf(" -> ");
    if (arrow !== -1) p = p.slice(arrow + 4);
    if (p.startsWith(`${SLICE_ROOT}/`)) slices.add(sliceOf(p));
  }
  return [...slices].sort();
}

// ---- append-only guard (ABSTRACTIONS.md / RATCHET.md) --------------------
// A write only passes silently if the new content still starts with the
// file's current content — heuristic for "this is a pure append," not a
// real diff. Pi's `edit` tool takes an ARRAY of {oldText, newText} pairs
// per call (unlike Claude Code's single old_string/new_string) — every
// pair must individually look like an append for the whole call to pass.
function isAppendOnlyPath(relPath: string): boolean {
  return relPath === "ABSTRACTIONS.md" || relPath === "RATCHET.md";
}

function looksLikeNonAppendEdit(edits: { oldText: string; newText: string }[]): boolean {
  return edits.some((e) => !e.newText.startsWith(e.oldText));
}

function looksLikeNonAppendWrite(absPath: string, newContent: string): boolean {
  if (!existsSync(absPath)) return false; // new file — nothing to preserve yet
  const current = readFileSync(absPath, "utf8");
  return !newContent.startsWith(current);
}

// ---- fence: tool_call ------------------------------------------------------
// `isToolCallEventType` (not a raw `event.toolName === "..."` check) is what
// lets TypeScript actually narrow `event.input`'s type — the union includes
// `CustomToolCallEvent` whose `toolName` is a plain `string`, so an inline
// `!==` comparison can't prove "this isn't a custom tool" the way the SDK's
// own type guard can. Confirmed by hand: `tsc` rejected the `!==`-based
// version with real type errors on every `event.input.*` access below.
async function fence(pi: ExtensionAPI, event: ToolCallEvent, ctx: ExtensionContext): Promise<ToolCallEventResult | undefined> {
  let rawPath: string;
  let toolLabel: "write" | "edit";
  let nonAppendCheck: (absPath: string) => boolean;

  if (isToolCallEventType("write", event)) {
    rawPath = event.input.path;
    toolLabel = "write";
    nonAppendCheck = (absPath) => looksLikeNonAppendWrite(absPath, event.input.content);
  } else if (isToolCallEventType("edit", event)) {
    rawPath = event.input.path;
    toolLabel = "edit";
    nonAppendCheck = () => looksLikeNonAppendEdit(event.input.edits);
  } else {
    return undefined;
  }

  const root = await repoRoot(pi, ctx);
  const abs = isAbsolute(rawPath) ? rawPath : resolvePath(ctx.cwd, rawPath);
  const rel = toRelPath(rawPath, ctx.cwd, root);

  // Checked BEFORE the frozen-paths ask below: a baseline file could also
  // match a frozen pattern (e.g. it lives under .claude/**), and deny must
  // win over ask when both apply — "never by hand" allows no confirmation
  // path at all, unlike a frozen-path write.
  if (matchesAny(rel, BASELINE_PATTERNS)) {
    return {
      block: true,
      reason: `${rel} is a tool-written baseline/suppression file — never edited by hand. Regenerate it (uv run mypy 2>&1 | grep ': error:' > .claude/mypy-baseline.txt) or use the /ratchet skill's prune.sh via bash instead.`,
    };
  }

  if (isAppendOnlyPath(rel)) {
    const nonAppend = nonAppendCheck(abs);
    if (nonAppend) {
      const reason = `${rel} is append-only — this ${toolLabel} doesn't look like a pure append. Confirm before writing.`;
      if (!ctx.hasUI) return { block: true, reason: `${reason} (no UI for confirmation)` };
      const ok = await ctx.ui.confirm(`Append-only ledger: ${rel}`, reason);
      if (!ok) return { block: true, reason: "Blocked by user" };
    }
  }

  if (matchesAny(rel, FROZEN_PATTERNS)) {
    const reason = `${rel} is a frozen path (see CLAUDE.md's Frozen paths section) — confirm this write.`;
    if (!ctx.hasUI) return { block: true, reason: `${reason} (no UI for confirmation)` };
    const ok = await ctx.ui.confirm(`Frozen path: ${rel}`, reason);
    if (!ok) return { block: true, reason: "Blocked by user" };
  }

  // The active slice is INFERRED from the working tree's current diff, not
  // a declared env var — no one has to remember to set anything. The first
  // write to any slice (on an otherwise-clean tree) establishes that slice
  // as active for the rest of this uncommitted change set; every
  // subsequent write to a DIFFERENT slice is denied until the first
  // slice's changes are committed (or discarded).
  if (SLICE_ROOT && rel.startsWith(`${SLICE_ROOT}/`)) {
    const target = sliceOf(rel);
    const active = await activeSlices(pi, ctx, root);
    if (active.length > 1) {
      return {
        block: true,
        reason: `The working tree already has uncommitted changes spanning multiple slices (${active.join(",")}) — commit or discard down to one before continuing.`,
      };
    }
    if (active.length === 1 && active[0] !== target) {
      return {
        block: true,
        reason: `${rel} is in slice '${target}', but the working tree already has uncommitted changes in slice '${active[0]}'. Commit (or discard) that slice's work before starting a different one — one slice per uncommitted change set. Cross-slice code goes through ${SHARED_ROOT}/, not a direct write.`,
      };
    }
  }

  return undefined;
}

// ---- feedback: tool_result -------------------------------------------------
// PostToolUse-equivalent: formats/lints the file just touched and appends
// findings to the tool result's content so the model sees them inline —
// never blocks (tool_result fires after the write already happened; there
// is nothing left to block).
async function feedback(pi: ExtensionAPI, event: ToolResultEvent, ctx: ExtensionContext): Promise<{ content: ToolResultEvent["content"] } | undefined> {
  // `isWriteToolResult`/`isEditToolResult` narrow which EVENT variant this
  // is (useful for `.details`'s type), but `ToolResultEventBase.input` is
  // `Record<string, unknown>` regardless — the SDK doesn't re-type inputs
  // at result time the way it does at call time — so `path` still needs a
  // runtime check, not just a type-guard call. Confirmed by hand: `tsc`
  // rejected treating `event.input.path` as `string` even after narrowing.
  if (!isWriteToolResult(event) && !isEditToolResult(event)) return undefined;
  const rawPathValue = event.input.path;
  if (typeof rawPathValue !== "string") return undefined;
  const rawPath = rawPathValue;
  if (!/\.(ts|tsx|js|jsx|mts|cts)$/.test(rawPath)) return undefined;

  const root = await repoRoot(pi, ctx);
  const abs = isAbsolute(rawPath) ? rawPath : resolvePath(ctx.cwd, rawPath);

  const findings: string[] = [];
  const prettier = await pi.exec("npx", ["--no-install", "prettier", "--check", abs], { cwd: root }).catch(() => null);
  if (prettier && prettier.code !== 0) findings.push(`prettier:\n${prettier.stdout}${prettier.stderr}`);
  const eslint = await pi.exec("npx", ["--no-install", "eslint", abs], { cwd: root }).catch(() => null);
  if (eslint && eslint.code !== 0) findings.push(`eslint:\n${eslint.stdout}${eslint.stderr}`);

  if (findings.length === 0) return undefined;
  return { content: [...event.content, { type: "text", text: findings.join("\n\n") }] };
}

// ---- gate: agent_settled ----------------------------------------------------
// Stop-hook-equivalent: refuses to let the agent settle until checks are
// clean. Pi has no direct "block completion" return value the way Claude
// Code's Stop hook does — the analogue is forcing another turn via
// `pi.sendUserMessage(reason)`, which (per Pi's own docs) sends
// immediately and triggers a new turn when the agent is idle, which is
// exactly the state `agent_settled` fires in.
//
// Skips entirely on a clean tree, same as gate.sh, so it can never trap a
// turn that touched no files. A small consecutive-retry cap guards against
// looping forever if the checks can never pass (e.g. a pre-existing broken
// test suite) — same safety concern Claude Code's own Stop hook loop has,
// addressed here explicitly since Pi has no documented equivalent to
// `stop_hook_active` to lean on.
const MAX_CONSECUTIVE_GATE_RETRIES = 3;
let consecutiveGateRetries = 0;

async function runCheck(pi: ExtensionAPI, root: string, label: string, command: string): Promise<string | undefined> {
  const [cmd, ...args] = command.split(" ");
  const result = await pi.exec(cmd, args, { cwd: root }).catch((err: unknown) => ({
    stdout: "",
    stderr: String(err),
    code: 1,
    killed: false,
  }));
  if (result.code !== 0) {
    const tail = `${result.stdout}\n${result.stderr}`.trim().split("\n").slice(-5).join(" ");
    return `${label}: ${tail}`;
  }
  return undefined;
}

async function gate(pi: ExtensionAPI, ctx: ExtensionContext): Promise<void> {
  const root = await repoRoot(pi, ctx);
  const { stdout: status } = await pi.exec("git", ["status", "--porcelain"], { cwd: root });
  if (!status.trim()) {
    consecutiveGateRetries = 0;
    return;
  }
  if (consecutiveGateRetries >= MAX_CONSECUTIVE_GATE_RETRIES) {
    consecutiveGateRetries = 0; // reset so the NEXT dirty-tree turn gets a fresh budget
    return;
  }

  const fails: string[] = [];
  for (const [label, cmd] of [
    ["format", CMD_FORMAT],
    ["typecheck", CMD_TYPECHECK],
    ["lint", CMD_LINT],
    ["test", CMD_TEST],
  ] as const) {
    const fail = await runCheck(pi, root, label, cmd);
    if (fail) fails.push(fail);
  }

  const diff = await pi.exec("git", ["diff", "--shortstat", "HEAD"], { cwd: root }).catch(() => null);
  if (diff) {
    const insertions = [...diff.stdout.matchAll(/(\d+) insertion/g)].reduce((s, m) => s + Number(m[1]), 0);
    const deletions = [...diff.stdout.matchAll(/(\d+) deletion/g)].reduce((s, m) => s + Number(m[1]), 0);
    const diffLines = insertions + deletions;
    if (diffLines > DIFF_BUDGET) {
      fails.push(
        `diff: ${diffLines} lines changed, budget is ${DIFF_BUDGET} — generated artifacts (baselines, lockfiles) are exempt if split into their own commit`,
      );
    }
  }

  if (fails.length > 0) {
    consecutiveGateRetries += 1;
    await pi.sendUserMessage(`Gate check failed — fix before finishing:\n\n${fails.join("\n")}`);
  } else {
    consecutiveGateRetries = 0;
  }
}

// ---- registration -----------------------------------------------------------
export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event, ctx) => fence(pi, event, ctx));
  pi.on("tool_result", async (event, ctx) => feedback(pi, event, ctx));
  pi.on("agent_settled", async (_event, ctx) => gate(pi, ctx));
}
